### ISSUE TITLE
Refresh Customization

### ISSUE THREAD

**Issue by Matt-MX** [Matt-MX/DisplayNameTags#10]
Currently the refresh trait is refreshing at a static 1 tick, make this customizable in the `config.yml`

```yml
defaults:
    # How often should we update holograms? (In millis)
    refresh-period: 50
```
