### ISSUE TITLE
Suggestion: Conditions

### ISSUE THREAD

**Issue by Zarkness** [Matt-MX/DisplayNameTags#12]
Add a system to create lines by condition either permissions or a placeholder

**Comment by Matt-MX** [comment]
You should be able to use [TAB's conditional placeholders](https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Conditional-placeholders) to achieve this

**Comment by Zarkness** [comment]
How can I configure the opacity of the background?

and to use the tab conditional placeholders how would it be? apart from configuring the placeholder in the tab clearly.

then as soon as I install the plugin and enter I get as well as I fix it I use the version of packetevents 2.5.1-SNAPSHOT, apart from that as I hide the user name that puts by default minecraft?

![image](https://github.com/user-attachments/assets/02207d2f-7e07-4c74-b8ad-218774101710)

**Comment by Zarkness** [comment]
Hi @Matt-MX I just encountered this problem and as you can see in the video I have set for example the user to have the nametag mvp and they try all the time to interleave/overwrite the default
https://github.com/user-attachments/assets/3d5a3953-86cc-49d1-9326-ce384ca7f7e0

**Comment by Matt-MX** [comment]
> How can I configure the opacity of the background?
> 
> and to use the tab conditional placeholders how would it be? apart from configuring the placeholder in the tab clearly.
> 
> then as soon as I install the plugin and enter I get as well as I fix it I use the version of packetevents 2.5.1-SNAPSHOT, apart from that as I hide the user name that puts by default minecraft?
> 
> ![image](https://private-user-images.githubusercontent.com/48263644/371484970-02207d2f-7e07-4c74-b8ad-218774101710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NjU5NDcsIm5iZiI6MTcyNzU2NTY0NywicGF0aCI6Ii80ODI2MzY0NC8zNzE0ODQ5NzAtMDIyMDdkMmYtN2UwNy00Yzc0LWI4YWQtMjE4Nzc0MTAxNzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDIzMjA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZmQ5NmMxNzE2MGExYjJmMmNjZTNhYjM1NWMxMDczZjhlMTIxMzU1NWRlNjIwZTc4NDYxYmQ0NGQyMmJlN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w6aQ--kMjG8K-9lSfuZmRotmWQyWsF0rvzb4MuSVC00)

e.g
`background: transparent|hex|white|red`

**Comment by Matt-MX** [comment]
> Hi @Matt-MX I just encountered this problem and as you can see in the video I have set for example the user to have the nametag mvp and they try all the time to interleave/overwrite the default https://github.com/user-attachments/assets/3d5a3953-86cc-49d1-9326-ce384ca7f7e0

Alright I can look at this tomorrow, it just requires me to implement the caching that I was meant to do before but was a bit lazy and put it off.

**Comment by Zarkness** [comment]
> > How can I configure the opacity of the background?
> 
> e.g `background: transparent|hex|white|red`

Okey Thanks


> > Hi @Matt-MX I just encountered this problem and as you can see in the video I have set for example the user to have the nametag mvp and they try all the time to interleave/overwrite the default https://github.com/user-attachments/assets/3d5a3953-86cc-49d1-9326-ce384ca7f7e0
> 
> Alright I can look at this tomorrow, it just requires me to implement the caching that I was meant to do before but was a bit lazy and put it off.

Okay, I'll be waiting

**Comment by Matt-MX** [comment]
Oops didn't mean to close, 

@Zarkness I've made some changes if you can try them in the latest dev build found here:
https://github.com/Matt-MX/DisplayNameTags/actions/runs/11093808038

**Comment by Zarkness** [comment]
ok, I'll try it now and let you know

**Comment by Zarkness** [comment]
The first problem I encountered.

It is when I edit the config and give /nametags-reload that I do not see the nametags, to fix it I have to enter and exit again.

The second problem I encountered.

Is that after giving reload to the plugin, exit, re-enter gives me network protocol error error, when in the previous version did not happen to me, to fix it I have to leave with a secondary account and re-enter then the account that gave me that error and let me enter, the error happens only with the first account that comes out after giving reload, I think it also happens without giving reload to the plugin.


Then when in background I put a hexadecimal color as for example #084cfbc the background becomes invisible, when you told me that it accepts hex colors.


As you can see in the videos

Video where is the plugin and I show the errors mentioned above --->


https://github.com/user-attachments/assets/6a074143-cfcc-4903-b5f5-a4161c9ddc52



Video where the plugin is not present and I show that I don't get the network protol error --->

https://github.com/user-attachments/assets/87c9ae7d-678c-4484-a70f-7b3e9be82f7e

**Comment by Zarkness** [comment]
@Matt-MX if you need anything let me know and I'll pass it on to you.

**Comment by Matt-MX** [comment]
Appears that reloading causes the network error #9

**Comment by Matt-MX** [comment]
@Zarkness Please try the latest dev build

https://github.com/Matt-MX/DisplayNameTags/actions/runs/11107934751

I've tested it myself and it seems to be stable!

**Comment by Matt-MX** [comment]
Idk how I keep closing this accidentally

**Comment by Matt-MX** [comment]
> it would be nice that the refresh was to update placeholders as for example of economy and so

are placeholders not currently updating? They should be

**Comment by Zarkness** [comment]
> are placeholders not currently updating? They should be

The placeholders do update, the problem is that when you reload that little display of the default nametag is still there.

**Comment by Matt-MX** [comment]
> The placeholders do update, the problem is that when you reload that little display of the default nametag is still there.

I don't really understand what you mean by that if you can provide a clip again, sorry

**Comment by Zarkness** [comment]
https://github.com/user-attachments/assets/38189f8e-1ec2-4a8f-8918-31e4694cf441

If you look closely in the video when the nametag is refreshed for a second or so you will see the default nametag.

**Comment by Zarkness** [comment]
I won't be home for another 4 or 5 hours. As soon as I get there, I'll send you the configuration.

**Comment by Matt-MX** [comment]
> and how do I do or activate debugging?

There isn't a debugging mode atm, I'll just have to do it myself really

**Comment by Zarkness** [comment]
this is my current config

```yml
# Should the player see their own tag?
show-self: false

sneak:
  # Should we modify the opacity of the tag's background when the player shifts?
  enabled: true
  opacity: 70

defaults:
  # If not enabled then plugin simulates vanilla name tags
  enabled: true
  # How often should we refresh tags (in milliseconds)
  refresh-every: 50
  # Lines of text to display.
  text:
    - "<white>%player_name%</white>"
    - "<blue>%player_ping%ms</blue>"
  # Background colour of the billboard.
  # You can use AARRGGBB hex codes e.g '#FF00FF00'
  # as well as RRGGBB hex codes e.g '#00FF00'
  # Otherwise you can use named text colours e.g 'white',
  # 'black' or 'red' as well as 'transparent'.
  background: '#aadd11'
  # Billboard display type.
  # You can choose 'center', 'vertical' or 'horizontal
  billboard: center
  text-shadow: true
  # Visual display range.
  # You can specify range in blocks or use 'default'
  # which will use the server's simulation distance.
  range: default
  # Gap above the head, closest to vanilla is 0.2
  gap: 0.2

# Permission based groups.
# Will only work if you have the "defaults" section enabled.
# Specify sub-groups that override the defaults.
# e.g
# groups:
#   vip:
#     background: red
#     ...
#
# Here, you would grant a user the permission "nametags.groups.vip"
# to receive a red background
groups:
  # e.g nametags.groups.vip
  vip:
    text:
      - " %kyorify_luckperms_prefix% %player_name% %luckperms_suffix%"
      - "<blue>%player_ping%ms</blue>"
      - 'bye'
    background: "#aa224d"
    billboard: center
    text-shadow: true
    range: default
    gap: 0.3
    refresh-every: 50
  mvp:
    text:
      - " %kyorify_luckperms_prefix% %player_name% %luckperms_suffix%"
      - "<blue>%player_ping%ms</blue>"
      - 'bye'
    background: "#aa224d"
    billboard: center
    text-shadow: true
    range: default
    gap: 0.3
    refresh-every: 50
  staff:
    background: red

# Extra features
# These will likely not work yet since they're experimental.
extra:
  # Should the name-tag be see-through if the player is glowing?
  glowing-feature: true
```
