### ISSUE TITLE
Legacy color codes

### ISSUE THREAD

**Issue by potatoru** [Matt-MX/DisplayNameTags#18]
Hi! Legacy color codes from placeholders won't work.

![Untitled](https://github.com/user-attachments/assets/a7c6457c-60b2-4bd2-be93-446a531fc937)

```
defaults:
  # If not enabled then plugin simulates vanilla name tags
  enabled: true
  text:
    - "%luckperms_meta_cm_group_prefix%<white>%player_name%</white>"
  background: black
  billboard: center
  text-shadow: true
  range: default
  gap: 0.2
```
