### ISSUE TITLE
Transparency Doesn't Seem to Work Correctly

### ISSUE THREAD

**Issue by Sixsoul** [Matt-MX/DisplayNameTags#4]
First thanks for this plugin! Great alternative now that TAB is removing their nametag feature.

I can't seem to make transparent background work properly, it seems to randomly flip between being transparent and just being the standard gray background.

Here is my config for reference:
```
# Should the player see their own tag?
show-self: true

sneak:
  # Should we modify the opacity of the tag's background when the player shifts?
  enabled: true
  opacity: 70

defaults:
  # If not enabled then plugin simulates vanilla name tags
  enabled: true
  text:
    - "<white>%luckperms_prefix%%player_name%</white>"
    - "<blue>Level %mmocore_level%</blue>"
  background: transparent
  billboard: center
  shadow: true
  range: 32
  gap: 0.2

groups:
  # e.g nametags.groups.vip
  default:
    background: transparent
  # mvp:
  #   background: green
  # staff:
  #   background: red
```

I am on paper 1.20.4
