### ISSUE TITLE
Possibility to support cosmetic plugins

### ISSUE THREAD

**Issue by Ranksu10** [Matt-MX/DisplayNameTags#49]
I've been wondering if it's possible to support cosmetics plugins like HMCCosmetics for example, where hat cosmetics are too big that you are not able to the nametags. So with the support it should increase the height of the nametag based on the cosmetic height so the nametag is visible.

**Comment by Matt-MX** [comment]
Looking at the HMC api, there is no way to get the height of a cosmetic, so the only way I can add support for this is if you manually configure each cosmetic:

Could look like this:

```yml
extras:
  HMCCosmetics:
    y-offsets:
      hat1: 3.0
      hat2: 1.0
```
